# ACT0301 - Limpieza de datos #


<ol>
    <li>Limpieza <strong>Basica</strong> de datos.</li>
    <li>Creación de Modelo</li>
    <li>Aplicación del Modelo a los datos.</li>
</ol>

<br>
<br>

<br>
<br>
<br>

In [336]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mutual_info_score
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction import DictVectorizer

In [337]:
df = pd.read_csv('../DataSets/WA_Fn-UseC_-Telco-Customer-Churn.csv')
print(len(df))
df.head().T

7043

,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

In [338]:
df=df.drop_duplicates()
df.drop(columns="gender")

,customerID,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [339]:
total_charges = pd.to_numeric(df.TotalCharges, errors='coerce')
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')
df.TotalCharges = df.TotalCharges.fillna(0)
df[total_charges.isnull()][['customerID', 'TotalCharges']]

      customerID  TotalCharges
488   4472-LVYGI           0.0
753   3115-CZMZD           0.0
936   5709-LVOEQ           0.0
1082  4367-NUYAO           0.0
1340  1371-DWPAZ           0.0
3331  7644-OMVMY           0.0
3826  3213-VVOLG           0.0
4380  2520-SGTTA           0.0
5218  2923-ARZLG           0.0
6670  4075-WKNIU           0.0
6754  2775-SEFEE           0.0

In [340]:
conver = lambda str: str.lower().str.replace(' ', '_').str.replace('-','_')

numerizar=lambda str: str.lower().str.replace('yes', '1').str.replace('no','0').str.replace('female','1').str.replace('male','0')


df.columns = conver(df.columns.str)


for col in list(df.dtypes[df.dtypes == 'object'].index):
    df[col] = conver(df[col].str)
    df[col] = numerizar(df[col].str)

df.head().T

,0,1,2,3,4
customerid,7590_vhveg,5575_gnvde,3668_qpybk,7795_cfocw,9237_hqitu
gender,1,0,0,0,1
seniorcitizen,0,0,0,0,0
partner,1,0,0,0,0
dependents,0,0,0,0,0
tenure,1,34,2,45,2
phoneservice,0,1,1,0,1
multiplelines,0_phone_service,0,0,0_phone_service,0
internetservice,dsl,dsl,dsl,dsl,fiber_optic
onlinesecurity,0,1,1,1,0
onlinebackup,1,0,1,0,0
deviceprotection,0,1,0,1,0
techsupport,0,0,0,1,0
streamingtv,0,0,0,0,0
streamingmovies,0,0,0,0,0
contract,month_to_month,one_year,month_to_month,one_year,month_to_month
paperlessbilling,1,0,1,0,1
paymentmethod,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,0,0,1,0,1

In [341]:
categorias = ['gender', 'seniorcitizen', 'partner', 'dependents','phoneservice', 'multiplelines', 'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport', 'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling', 'paymentmethod']

numericos=['tenure', 'monthlycharges', 'totalcharges']

#Cuenta las distan posibilidades que encuentra en una columna.
df[categorias].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [342]:
#Division de los datos

#En este caso valos a separar 80% para entramiento y un 20% para test
df_train_full, df_test = train_test_split(df, test_size=0.2, random_state=1)

df_train, df_val = train_test_split(df_train_full, test_size=0.33, random_state=1)
y_train = df_train.churn.values
y_val = df_val.churn.values




del df_train['churn']
del df_val['churn']

df_train.head().T

df_train_full.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
1814,5442_pptjy,0,0,1,1,12,1,0,0,0_internet_service,...,0_internet_service,0_internet_service,0_internet_service,0_internet_service,two_year,0,mailed_check,19.70,258.35,0
5946,6261_rcvns,1,0,0,0,42,1,0,dsl,1,...,1,1,0,1,one_year,0,credit_card_(automatic),73.90,3160.55,1
3881,2176_osjuv,0,0,1,0,71,1,1,dsl,1,...,0,1,0,0,two_year,0,bank_transfer_(automatic),65.15,4681.75,0
2389,6161_erdgd,0,0,1,1,71,1,1,dsl,1,...,1,1,1,1,one_year,0,electronic_check,85.45,6300.85,0
3676,2364_ufrom,0,0,0,0,30,1,0,dsl,1,...,0,1,1,0,one_year,0,electronic_check,70.40,2044.75,0

## Analisis de importancia

In [343]:
global_mean = df_train_full.churn.mean()
round(global_mean, 3)
df_train_full.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
1814,5442_pptjy,0,0,1,1,12,1,0,0,0_internet_service,...,0_internet_service,0_internet_service,0_internet_service,0_internet_service,two_year,0,mailed_check,19.70,258.35,0
5946,6261_rcvns,1,0,0,0,42,1,0,dsl,1,...,1,1,0,1,one_year,0,credit_card_(automatic),73.90,3160.55,1
3881,2176_osjuv,0,0,1,0,71,1,1,dsl,1,...,0,1,0,0,two_year,0,bank_transfer_(automatic),65.15,4681.75,0
2389,6161_erdgd,0,0,1,1,71,1,1,dsl,1,...,1,1,1,1,one_year,0,electronic_check,85.45,6300.85,0
3676,2364_ufrom,0,0,0,0,30,1,0,dsl,1,...,0,1,1,0,one_year,0,electronic_check,70.40,2044.75,0

In [344]:

#Vamo a averiguar cuales columnas son mas importantes para el analisis para poder discriminarlas si es necesario.

media = df_train_full.churn.mean()
round(media, 3)

calculate_mi = lambda col: mutual_info_score(col, df_train_full.churn)

df_mi = df_train_full[categorias].apply(calculate_mi)
df_mi = df_mi.sort_values(ascending=False).to_frame(name='Importancia')
df_mi

                  Importancia
contract             0.098320
onlinesecurity       0.063085
techsupport          0.061032
internetservice      0.055868
onlinebackup         0.046923
deviceprotection     0.043453
paymentmethod        0.043210
streamingtv          0.031853
streamingmovies      0.031581
paperlessbilling     0.017589
dependents           0.012346
partner              0.009968
seniorcitizen        0.009410
multiplelines        0.000857
phoneservice         0.000229
gender               0.000117

Podemos observar que las 3 ultimas columnas [gender,phoneservice,multiplelines] no son muy importantes para el analisis en cuestión.

## Entrenamiento del modelo y vectorización

In [345]:
train_dict = df_train[categorias + numericos].to_dict(orient='records')
dict(sorted(train_dict[0].items()))

{'contract': 'month_to_month',
 'dependents': '0',
 'deviceprotection': '0',
 'gender': '0',
 'internetservice': 'fiber_optic',
 'monthlycharges': 85.55,
 'multiplelines': '0',
 'onlinebackup': '1',
 'onlinesecurity': '0',
 'paperlessbilling': '1',
 'partner': '0',
 'paymentmethod': 'electronic_check',
 'phoneservice': '1',
 'seniorcitizen': 1,
 'streamingmovies': '1',
 'streamingtv': '0',
 'techsupport': '0',
 'tenure': 5,
 'totalcharges': 408.5}

In [346]:
dv = DictVectorizer(sparse=False)
dv.fit(train_dict)

DictVectorizer(sparse=False)

In [347]:
X_train = dv.transform(train_dict)
X_train[0]

array([  1.  ,   0.  ,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ,
         1.  ,   0.  ,   0.  ,   0.  ,   1.  ,  85.55,   1.  ,   0.  ,
         0.  ,   0.  ,   0.  ,   1.  ,   1.  ,   0.  ,   0.  ,   0.  ,
         1.  ,   1.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ,
         1.  ,   1.  ,   0.  ,   0.  ,   1.  ,   1.  ,   0.  ,   0.  ,
         1.  ,   0.  ,   0.  ,   5.  , 408.5 ])

In [348]:
dv.get_feature_names_out()

array(['contract=month_to_month', 'contract=one_year',
       'contract=two_year', 'dependents=0', 'dependents=1',
       'deviceprotection=0', 'deviceprotection=0_internet_service',
       'deviceprotection=1', 'gender=0', 'gender=1', 'internetservice=0',
       'internetservice=dsl', 'internetservice=fiber_optic',
       'monthlycharges', 'multiplelines=0',
       'multiplelines=0_phone_service', 'multiplelines=1',
       'onlinebackup=0', 'onlinebackup=0_internet_service',
       'onlinebackup=1', 'onlinesecurity=0',
       'onlinesecurity=0_internet_service', 'onlinesecurity=1',
       'paperlessbilling=0', 'paperlessbilling=1', 'partner=0',
       'partner=1', 'paymentmethod=bank_transfer_(automatic)',
       'paymentmethod=credit_card_(automatic)',
       'paymentmethod=electronic_check', 'paymentmethod=mailed_check',
       'phoneservice=0', 'phoneservice=1', 'seniorcitizen',
       'streamingmovies=0', 'streamingmovies=0_internet_service',
       'streamingmovies=1', 'streamingtv=0',
       'streamingtv=0_internet_service', 'streamingtv=1', 'techsupport=0',
       'techsupport=0_internet_service', 'techsupport=1', 'tenure',
       'totalcharges'], dtype=object)

In [349]:
model = LogisticRegression(solver='liblinear')
model.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [350]:
val_dict = df_val[categorias + numericos].to_dict(orient='records')
X_val = dv.transform(val_dict)
y_pred = model.predict_proba(X_val)
y_pred

array([[0.99142715, 0.00857285],
       [0.79028891, 0.20971109],
       [0.78364671, 0.21635329],
       ...,
       [0.35664365, 0.64335635],
       [0.81056045, 0.18943955],
       [0.87262042, 0.12737958]])

In [351]:
y_pred = model.predict_proba(X_val)[:, 1]
y_pred

array([0.00857285, 0.20971109, 0.21635329, ..., 0.64335635, 0.18943955,
       0.12737958])

In [352]:
churn = y_pred >= 0.58
y_val=(y_val == '1').astype(int)
churn=(churn == True).astype(int)

array([False, False, False, ...,  True, False, False])

In [357]:


print(f' La puntuacion de acierto es del : \n  {round((y_val == churn).mean(), 3) }%')

 La puntuacion de acierto es del :
  0.812%